use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'HHSimpleTool_Example' do
  pod 'HHSimpleTool', :path => '../'
  
  pod 'SDWebImage', '~> 5.0'

  target 'HHSimpleTool_Tests' do
    inherit! :search_paths

    
  end
end
